set-option -g mouse on
set-option -g history-limit 10000
setw -g mode-keys vi

bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Split panes
bind | split-window -h
bind - split-window -v

# Easy movement between panes (works well with vim-tmux-navigator)
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-j select-pane -D
bind -n C-k select-pane -U

# Status bar
set -g status-bg black
set -g status-fg white
set -g status-left '#[fg=green]#H'
set -g status-right '#[fg=yellow]%Y-%m-%d %H:%M'
